// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { getListeMarchesMarcheGetResponseTransformer, getMarcheMarcheUidGetResponseTransformer } from './transformers.gen';
import type { GetErreursImportErreursImportGetData, GetErreursImportErreursImportGetErrors, GetErreursImportErreursImportGetResponses, GetIndicateursMarcheIndicateursGetData, GetIndicateursMarcheIndicateursGetErrors, GetIndicateursMarcheIndicateursGetResponses, GetListeConcessionsContratConcessionGetData, GetListeConcessionsContratConcessionGetErrors, GetListeConcessionsContratConcessionGetResponses, GetListeMarchesMarcheGetData, GetListeMarchesMarcheGetErrors, GetListeMarchesMarcheGetResponses, GetMarcheMarcheUidGetData, GetMarcheMarcheUidGetErrors, GetMarcheMarcheUidGetResponses, GetMarchesParCcagMarcheCcagGetData, GetMarchesParCcagMarcheCcagGetErrors, GetMarchesParCcagMarcheCcagGetResponses, GetMarchesParDepartementMarcheDepartementGetData, GetMarchesParDepartementMarcheDepartementGetResponses, GetMarchesParNatureMarcheNatureGetData, GetMarchesParNatureMarcheNatureGetErrors, GetMarchesParNatureMarcheNatureGetResponses, GetMarchesParProcedureMarcheProcedureGetData, GetMarchesParProcedureMarcheProcedureGetErrors, GetMarchesParProcedureMarcheProcedureGetResponses, GetStatsErreursErreursImportStatsGetData, GetStatsErreursErreursImportStatsGetResponses, GetStructureStructureUidGetData, GetStructureStructureUidGetErrors, GetStructureStructureUidGetResponses, ListAcheteursStructureAcheteurGetData, ListAcheteursStructureAcheteurGetErrors, ListAcheteursStructureAcheteurGetResponses, ListVendeursStructureVendeurGetData, ListVendeursStructureVendeurGetErrors, ListVendeursStructureVendeurGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Erreurs Import
 */
export const getErreursImportErreursImportGet = <ThrowOnError extends boolean = false>(options?: Options<GetErreursImportErreursImportGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetErreursImportErreursImportGetResponses, GetErreursImportErreursImportGetErrors, ThrowOnError>({
        url: '/erreurs-import/',
        ...options
    });
};

/**
 * Get Stats Erreurs
 */
export const getStatsErreursErreursImportStatsGet = <ThrowOnError extends boolean = false>(options?: Options<GetStatsErreursErreursImportStatsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetStatsErreursErreursImportStatsGetResponses, unknown, ThrowOnError>({
        url: '/erreurs-import/stats',
        ...options
    });
};

/**
 * Get Liste Marches
 */
export const getListeMarchesMarcheGet = <ThrowOnError extends boolean = false>(options?: Options<GetListeMarchesMarcheGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetListeMarchesMarcheGetResponses, GetListeMarchesMarcheGetErrors, ThrowOnError>({
        responseTransformer: getListeMarchesMarcheGetResponseTransformer,
        url: '/marche/',
        ...options
    });
};

/**
 * Get Marches Par Procedure
 */
export const getMarchesParProcedureMarcheProcedureGet = <ThrowOnError extends boolean = false>(options?: Options<GetMarchesParProcedureMarcheProcedureGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMarchesParProcedureMarcheProcedureGetResponses, GetMarchesParProcedureMarcheProcedureGetErrors, ThrowOnError>({
        url: '/marche/procedure',
        ...options
    });
};

/**
 * Get Marches Par Nature
 */
export const getMarchesParNatureMarcheNatureGet = <ThrowOnError extends boolean = false>(options?: Options<GetMarchesParNatureMarcheNatureGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMarchesParNatureMarcheNatureGetResponses, GetMarchesParNatureMarcheNatureGetErrors, ThrowOnError>({
        url: '/marche/nature',
        ...options
    });
};

/**
 * Get Marches Par Ccag
 */
export const getMarchesParCcagMarcheCcagGet = <ThrowOnError extends boolean = false>(options?: Options<GetMarchesParCcagMarcheCcagGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMarchesParCcagMarcheCcagGetResponses, GetMarchesParCcagMarcheCcagGetErrors, ThrowOnError>({
        url: '/marche/ccag',
        ...options
    });
};

/**
 * Get Indicateurs
 */
export const getIndicateursMarcheIndicateursGet = <ThrowOnError extends boolean = false>(options?: Options<GetIndicateursMarcheIndicateursGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetIndicateursMarcheIndicateursGetResponses, GetIndicateursMarcheIndicateursGetErrors, ThrowOnError>({
        url: '/marche/indicateurs',
        ...options
    });
};

/**
 * Get Marches Par Departement
 */
export const getMarchesParDepartementMarcheDepartementGet = <ThrowOnError extends boolean = false>(options?: Options<GetMarchesParDepartementMarcheDepartementGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMarchesParDepartementMarcheDepartementGetResponses, unknown, ThrowOnError>({
        url: '/marche/departement',
        ...options
    });
};

/**
 * Get Marche
 */
export const getMarcheMarcheUidGet = <ThrowOnError extends boolean = false>(options: Options<GetMarcheMarcheUidGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetMarcheMarcheUidGetResponses, GetMarcheMarcheUidGetErrors, ThrowOnError>({
        responseTransformer: getMarcheMarcheUidGetResponseTransformer,
        url: '/marche/{uid}',
        ...options
    });
};

/**
 * Get Liste Concessions
 */
export const getListeConcessionsContratConcessionGet = <ThrowOnError extends boolean = false>(options?: Options<GetListeConcessionsContratConcessionGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetListeConcessionsContratConcessionGetResponses, GetListeConcessionsContratConcessionGetErrors, ThrowOnError>({
        url: '/contrat-concession/',
        ...options
    });
};

/**
 * List Acheteurs
 */
export const listAcheteursStructureAcheteurGet = <ThrowOnError extends boolean = false>(options?: Options<ListAcheteursStructureAcheteurGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListAcheteursStructureAcheteurGetResponses, ListAcheteursStructureAcheteurGetErrors, ThrowOnError>({
        url: '/structure/acheteur',
        ...options
    });
};

/**
 * List Vendeurs
 */
export const listVendeursStructureVendeurGet = <ThrowOnError extends boolean = false>(options?: Options<ListVendeursStructureVendeurGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListVendeursStructureVendeurGetResponses, ListVendeursStructureVendeurGetErrors, ThrowOnError>({
        url: '/structure/vendeur',
        ...options
    });
};

/**
 * Get Structure
 */
export const getStructureStructureUidGet = <ThrowOnError extends boolean = false>(options: Options<GetStructureStructureUidGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetStructureStructureUidGetResponses, GetStructureStructureUidGetErrors, ThrowOnError>({
        url: '/structure/{uid}',
        ...options
    });
};
