// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetErreursImportErreursImportGetData, GetErreursImportErreursImportGetResponses, GetListeMarchesMarcheGetData, GetListeMarchesMarcheGetResponses, GetListeMarchesMarcheGetErrors, GetMarchesParProcedureMarcheProcedureGetData, GetMarchesParProcedureMarcheProcedureGetResponses, GetMarchesParProcedureMarcheProcedureGetErrors, GetMarchesParCcagMarcheCcagGetData, GetMarchesParCcagMarcheCcagGetResponses, GetMarchesParCcagMarcheCcagGetErrors, GetIndicateursMarcheIndicateursGetData, GetIndicateursMarcheIndicateursGetResponses, GetIndicateursMarcheIndicateursGetErrors, GetMarchesParDepartementMarcheDepartementGetData, GetMarchesParDepartementMarcheDepartementGetResponses, GetListeConcessionsContratConcessionGetData, GetListeConcessionsContratConcessionGetResponses, GetListeConcessionsContratConcessionGetErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';
import { getListeMarchesMarcheGetResponseTransformer, getListeConcessionsContratConcessionGetResponseTransformer } from './transformers.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Erreurs Import
 */
export const getErreursImportErreursImportGet = <ThrowOnError extends boolean = false>(options?: Options<GetErreursImportErreursImportGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetErreursImportErreursImportGetResponses, unknown, ThrowOnError>({
        url: '/erreurs-import/',
        ...options
    });
};

/**
 * Get Liste Marches
 */
export const getListeMarchesMarcheGet = <ThrowOnError extends boolean = false>(options?: Options<GetListeMarchesMarcheGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetListeMarchesMarcheGetResponses, GetListeMarchesMarcheGetErrors, ThrowOnError>({
        responseTransformer: getListeMarchesMarcheGetResponseTransformer,
        url: '/marche/',
        ...options
    });
};

/**
 * Get Marches Par Procedure
 */
export const getMarchesParProcedureMarcheProcedureGet = <ThrowOnError extends boolean = false>(options?: Options<GetMarchesParProcedureMarcheProcedureGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMarchesParProcedureMarcheProcedureGetResponses, GetMarchesParProcedureMarcheProcedureGetErrors, ThrowOnError>({
        url: '/marche/procedure',
        ...options
    });
};

/**
 * Get Marches Par Ccag
 */
export const getMarchesParCcagMarcheCcagGet = <ThrowOnError extends boolean = false>(options?: Options<GetMarchesParCcagMarcheCcagGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMarchesParCcagMarcheCcagGetResponses, GetMarchesParCcagMarcheCcagGetErrors, ThrowOnError>({
        url: '/marche/ccag',
        ...options
    });
};

/**
 * Get Indicateurs
 */
export const getIndicateursMarcheIndicateursGet = <ThrowOnError extends boolean = false>(options?: Options<GetIndicateursMarcheIndicateursGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetIndicateursMarcheIndicateursGetResponses, GetIndicateursMarcheIndicateursGetErrors, ThrowOnError>({
        url: '/marche/indicateurs',
        ...options
    });
};

/**
 * Get Marches Par Departement
 */
export const getMarchesParDepartementMarcheDepartementGet = <ThrowOnError extends boolean = false>(options?: Options<GetMarchesParDepartementMarcheDepartementGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMarchesParDepartementMarcheDepartementGetResponses, unknown, ThrowOnError>({
        url: '/marche/departement',
        ...options
    });
};

/**
 * Get Liste Concessions
 */
export const getListeConcessionsContratConcessionGet = <ThrowOnError extends boolean = false>(options?: Options<GetListeConcessionsContratConcessionGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetListeConcessionsContratConcessionGetResponses, GetListeConcessionsContratConcessionGetErrors, ThrowOnError>({
        responseTransformer: getListeConcessionsContratConcessionGetResponseTransformer,
        url: '/contrat-concession/',
        ...options
    });
};