// This file is auto-generated by @hey-api/openapi-ts

import type { GetConcessionResponse, GetListeConcessionsResponse, GetListeMarchesResponse, GetMarcheResponse, GetStructureResponse } from './types.gen';

const marcheAllegeDtoSchemaResponseTransformer = (data: any) => {
    data.actes_sous_traitance = data.actes_sous_traitance.map((item: any) => {
        return acteSousTraitanceDtoSchemaResponseTransformer(item);
    });
    data.date_notification = new Date(data.date_notification);
    return data;
};

const acteSousTraitanceDtoSchemaResponseTransformer = (data: any) => {
    data.date_notification = new Date(data.date_notification);
    data.date_publication = new Date(data.date_publication);
    return data;
};

export const getListeMarchesResponseTransformer = async (data: any): Promise<GetListeMarchesResponse> => {
    data = data.map((item: any) => {
        return marcheAllegeDtoSchemaResponseTransformer(item);
    });
    return data;
};

const marcheDtoSchemaResponseTransformer = (data: any) => {
    if (data.accord_cadre) {
        data.accord_cadre = marcheDtoSchemaResponseTransformer(data.accord_cadre);
    }
    data.actes_sous_traitance = data.actes_sous_traitance.map((item: any) => {
        return acteSousTraitanceDtoSchemaResponseTransformer(item);
    });
    data.date_notification = new Date(data.date_notification);
    if (data.date_publication) {
        data.date_publication = new Date(data.date_publication);
    }
    data.modifications = data.modifications.map((item: any) => {
        return modificationMarcheDtoSchemaResponseTransformer(item);
    });
    return data;
};

const modificationMarcheDtoSchemaResponseTransformer = (data: any) => {
    data.date_notification = new Date(data.date_notification);
    data.date_publication = new Date(data.date_publication);
    return data;
};

export const getMarcheResponseTransformer = async (data: any): Promise<GetMarcheResponse> => {
    data = marcheDtoSchemaResponseTransformer(data);
    return data;
};

const contratConcessionDtoSchemaResponseTransformer = (data: any) => {
    data.date_signature = new Date(data.date_signature);
    data.date_publication = new Date(data.date_publication);
    data.date_debut_execution = new Date(data.date_debut_execution);
    if (data.donnees_execution) {
        data.donnees_execution = data.donnees_execution.map((item: any) => {
            return donneeExecutionDtoSchemaResponseTransformer(item);
        });
    }
    return data;
};

const donneeExecutionDtoSchemaResponseTransformer = (data: any) => {
    data.date_publication = new Date(data.date_publication);
    return data;
};

export const getListeConcessionsResponseTransformer = async (data: any): Promise<GetListeConcessionsResponse> => {
    data = data.map((item: any) => {
        return contratConcessionDtoSchemaResponseTransformer(item);
    });
    return data;
};

export const getConcessionResponseTransformer = async (data: any): Promise<GetConcessionResponse> => {
    data = contratConcessionDtoSchemaResponseTransformer(data);
    return data;
};

const structureEtendueDtoSchemaResponseTransformer = (data: any) => {
    if (data.date_creation) {
        data.date_creation = new Date(data.date_creation);
    }
    return data;
};

export const getStructureResponseTransformer = async (data: any): Promise<GetStructureResponse> => {
    data = structureEtendueDtoSchemaResponseTransformer(data);
    return data;
};
