// This file is auto-generated by @hey-api/openapi-ts

import type { GetListeMarchesMarcheGetResponse, GetListeConcessionsContratConcessionGetResponse } from './types.gen';

const acteSousTraitanceDtoSchemaResponseTransformer = (data: any) => {
    data.date_notification = new Date(data.date_notification);
    data.date_publication = new Date(data.date_publication);
    return data;
};

const modificationMarcheDtoSchemaResponseTransformer = (data: any) => {
    data.date_notification = new Date(data.date_notification);
    data.date_publication = new Date(data.date_publication);
    return data;
};

const marcheDtoSchemaResponseTransformer = (data: any) => {
    if (data.accord_cadre) {
        data.accord_cadre = marcheDtoSchemaResponseTransformer(data.accord_cadre);
    }
    data.actes_sous_traitance = data.actes_sous_traitance.map((item: any) => {
        return acteSousTraitanceDtoSchemaResponseTransformer(item);
    });
    data.date_notification = new Date(data.date_notification);
    if (data.date_publication) {
        data.date_publication = new Date(data.date_publication);
    }
    data.modifications = data.modifications.map((item: any) => {
        return modificationMarcheDtoSchemaResponseTransformer(item);
    });
    return data;
};

export const getListeMarchesMarcheGetResponseTransformer = async (data: any): Promise<GetListeMarchesMarcheGetResponse> => {
    data = data.map((item: any) => {
        return marcheDtoSchemaResponseTransformer(item);
    });
    return data;
};

const donneeExecutionDtoSchemaResponseTransformer = (data: any) => {
    data.date_publication = new Date(data.date_publication);
    return data;
};

const modificationConcessionDtoSchemaResponseTransformer = (data: any) => {
    data.date_signature = new Date(data.date_signature);
    data.date_publication = new Date(data.date_publication);
    return data;
};

const contratConcessionDtoSchemaResponseTransformer = (data: any) => {
    data.date_signature = new Date(data.date_signature);
    data.date_publication = new Date(data.date_publication);
    data.date_debut_execution = new Date(data.date_debut_execution);
    data.donnees_execution = data.donnees_execution.map((item: any) => {
        return donneeExecutionDtoSchemaResponseTransformer(item);
    });
    data.modifications = data.modifications.map((item: any) => {
        return modificationConcessionDtoSchemaResponseTransformer(item);
    });
    return data;
};

export const getListeConcessionsContratConcessionGetResponseTransformer = async (data: any): Promise<GetListeConcessionsContratConcessionGetResponse> => {
    data = data.map((item: any) => {
        return contratConcessionDtoSchemaResponseTransformer(item);
    });
    return data;
};