// This file is auto-generated by @hey-api/openapi-ts

/**
 * ActeSousTraitanceDto
 */
export type ActeSousTraitanceDto = {
    /**
     * Uid
     */
    uid: number;
};

/**
 * ConsiderationsEnvironnementales
 */
export const ConsiderationsEnvironnementales = {
    CRITÈRE_ENVIRONNEMENTAL: 'Critère environnemental',
    CLAUSE_ENVIRONNEMENTALE: 'Clause environnementale',
    PAS_DE_CONSIDÉRATION_ENVIRONNEMENTALE: 'Pas de considération environnementale'
} as const;

/**
 * ConsiderationsEnvironnementales
 */
export type ConsiderationsEnvironnementales = (typeof ConsiderationsEnvironnementales)[keyof typeof ConsiderationsEnvironnementales];

/**
 * ConsiderationsSociales
 */
export const ConsiderationsSociales = {
    CRITÈRE_SOCIAL: 'Critère social',
    CLAUSE_SOCIALE: 'Clause sociale',
    MARCHÉ_RÉSERVÉ: 'Marché réservé',
    CONCESSION_RÉSERVÉ: 'Concession réservé',
    PAS_DE_CONSIDÉRATION_SOCIALE: 'Pas de considération sociale'
} as const;

/**
 * ConsiderationsSociales
 */
export type ConsiderationsSociales = (typeof ConsiderationsSociales)[keyof typeof ConsiderationsSociales];

/**
 * ContratConcessionDto
 */
export type ContratConcessionDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: number;
    autorite_concedante: StructureDto;
    nature: NatureConcession | null;
    /**
     * Objet
     */
    objet: string;
    procedure: ProcedureConcession | null;
    /**
     * Duree Mois
     */
    duree_mois: number;
    /**
     * Date Signature
     */
    date_signature: Date;
    /**
     * Date Publication
     */
    date_publication: Date;
    /**
     * Date Debut Execution
     */
    date_debut_execution: Date;
    /**
     * Valeur Globale
     */
    valeur_globale: string;
    /**
     * Montant Subvention Publique
     */
    montant_subvention_publique: string;
    /**
     * Donnees Execution
     */
    donnees_execution: Array<DonneeExecutionDto>;
    /**
     * Concessionnaires
     */
    concessionnaires: Array<StructureDto>;
    /**
     * Considerations Sociales
     */
    considerations_sociales: Array<ConsiderationsSociales>;
    /**
     * Considerations Environnementales
     */
    considerations_environnementales: Array<ConsiderationsEnvironnementales>;
    /**
     * Modifications
     */
    modifications: Array<ModificationConcessionDto>;
};

/**
 * DecpMalFormeDto
 */
export type DecpMalFormeDto = {
    /**
     * Decp
     */
    decp: unknown;
    /**
     * Erreurs
     */
    erreurs: Array<ErreurDto>;
};

/**
 * DonneeExecutionDto
 */
export type DonneeExecutionDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: number;
    /**
     * Uid Contrat Concession
     */
    uid_contrat_concession: number;
    /**
     * Date Publication
     */
    date_publication: Date;
    /**
     * Depenses Investissement
     */
    depenses_investissement: string;
    /**
     * Tarifs
     */
    tarifs: Array<TarifDto>;
};

/**
 * ErreurDto
 */
export type ErreurDto = {
    /**
     * Type
     */
    type: string;
    /**
     * Localisation
     */
    localisation: string;
    /**
     * Message
     */
    message: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IndicateursDto
 */
export type IndicateursDto = {
    /**
     * Periode
     */
    periode: number | null;
    /**
     * Nb Contrats
     */
    nb_contrats: number;
    /**
     * Montant Total
     */
    montant_total: string | null;
    /**
     * Nb Acheteurs
     */
    nb_acheteurs: number;
    /**
     * Nb Fournisseurs
     */
    nb_fournisseurs: number;
    /**
     * Nb Sous Traitance
     */
    nb_sous_traitance: number;
    /**
     * Nb Innovant
     */
    nb_innovant: number;
};

/**
 * MarcheAllegeDto
 */
export type MarcheAllegeDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: string;
    acheteur: StructureDto;
    /**
     * Objet
     */
    objet: string;
    /**
     * Cpv
     * Nomenclature européenne permettant d'identifier les catégories de biens et de service faisant l'objet du marché (http://simap.ted.europa.eu/web/simap/cpv). Exemple: 45112500 (même si toléré, il préférable d'omettre le caractère de contrôle (-9))
     */
    cpv: string;
    /**
     * Sous Traitance Declaree
     */
    sous_traitance_declaree: boolean;
    /**
     * Actes Sous Traitance
     */
    actes_sous_traitance: Array<ActeSousTraitanceDto>;
    /**
     * Date Notification
     */
    date_notification: Date;
    /**
     * Montant
     */
    montant: string;
    /**
     * Titulaires
     */
    titulaires: Array<StructureDto>;
};

/**
 * MarcheCcagDto
 */
export type MarcheCcagDto = {
    /**
     * Ccag
     */
    ccag: number | null;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * MarcheDepartementDto
 */
export type MarcheDepartementDto = {
    /**
     * Code
     */
    code: string;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * MarcheProcedureDto
 */
export type MarcheProcedureDto = {
    /**
     * Procedure
     */
    procedure: number | null;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * ModificationConcessionDto
 */
export type ModificationConcessionDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: number;
    /**
     * Date Signature
     */
    date_signature: Date;
    /**
     * Date Publication
     */
    date_publication: Date;
    /**
     * Duree Mois
     */
    duree_mois: number | null;
    /**
     * Valeur Globale
     */
    valeur_globale: string | null;
};

/**
 * NatureConcession
 */
export const NatureConcession = {
    CONCESSION_DE_TRAVAUX: 'Concession de travaux',
    CONCESSION_DE_SERVICE: 'Concession de service',
    CONCESSION_DE_SERVICE_PUBLIC: 'Concession de service public',
    DÉLÉGATION_DE_SERVICE_PUBLIC: 'Délégation de service public'
} as const;

/**
 * NatureConcession
 */
export type NatureConcession = (typeof NatureConcession)[keyof typeof NatureConcession];

/**
 * ProcedureConcession
 */
export const ProcedureConcession = {
    PROCÉDURE_NÉGOCIÉE_OUVERTE: 'Procédure négociée ouverte',
    PROCÉDURE_NON_NÉGOCIÉE_OUVERTE: 'Procédure non négociée ouverte',
    PROCÉDURE_NÉGOCIÉE_RESTREINTE: 'Procédure négociée restreinte',
    PROCÉDURE_NON_NÉGOCIÉE_RESTREINTE: 'Procédure non négociée restreinte'
} as const;

/**
 * ProcedureConcession
 */
export type ProcedureConcession = (typeof ProcedureConcession)[keyof typeof ProcedureConcession];

/**
 * StructureAggMarchesDto
 */
export type StructureAggMarchesDto = {
    structure: StructureDto;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nb Contrats
     */
    nb_contrats: number;
};

/**
 * StructureDto
 */
export type StructureDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Identifiant
     */
    identifiant: string;
    /**
     * Type Identifiant
     */
    type_identifiant: string;
    /**
     * Vendeur
     */
    vendeur: boolean;
    /**
     * Acheteur
     */
    acheteur: boolean;
};

/**
 * TarifDto
 */
export type TarifDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Uid Donnee Execution
     */
    uid_donnee_execution: number;
    /**
     * Intitule
     */
    intitule: string;
    /**
     * Tarif
     */
    tarif: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetErreursImportErreursImportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/erreurs-import/';
};

export type GetErreursImportErreursImportGetResponses = {
    /**
     * Response Get Erreurs Import Erreurs Import  Get
     * Successful Response
     */
    200: Array<DecpMalFormeDto>;
};

export type GetErreursImportErreursImportGetResponse = GetErreursImportErreursImportGetResponses[keyof GetErreursImportErreursImportGetResponses];

export type GetListeMarchesMarcheGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/';
};

export type GetListeMarchesMarcheGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListeMarchesMarcheGetError = GetListeMarchesMarcheGetErrors[keyof GetListeMarchesMarcheGetErrors];

export type GetListeMarchesMarcheGetResponses = {
    /**
     * Response Get Liste Marches Marche  Get
     * Successful Response
     */
    200: Array<MarcheAllegeDto>;
};

export type GetListeMarchesMarcheGetResponse = GetListeMarchesMarcheGetResponses[keyof GetListeMarchesMarcheGetResponses];

export type GetMarchesParProcedureMarcheProcedureGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/procedure';
};

export type GetMarchesParProcedureMarcheProcedureGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarchesParProcedureMarcheProcedureGetError = GetMarchesParProcedureMarcheProcedureGetErrors[keyof GetMarchesParProcedureMarcheProcedureGetErrors];

export type GetMarchesParProcedureMarcheProcedureGetResponses = {
    /**
     * Response Get Marches Par Procedure Marche Procedure Get
     * Successful Response
     */
    200: Array<MarcheProcedureDto>;
};

export type GetMarchesParProcedureMarcheProcedureGetResponse = GetMarchesParProcedureMarcheProcedureGetResponses[keyof GetMarchesParProcedureMarcheProcedureGetResponses];

export type GetMarchesParCcagMarcheCcagGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/ccag';
};

export type GetMarchesParCcagMarcheCcagGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarchesParCcagMarcheCcagGetError = GetMarchesParCcagMarcheCcagGetErrors[keyof GetMarchesParCcagMarcheCcagGetErrors];

export type GetMarchesParCcagMarcheCcagGetResponses = {
    /**
     * Response Get Marches Par Ccag Marche Ccag Get
     * Successful Response
     */
    200: Array<MarcheCcagDto>;
};

export type GetMarchesParCcagMarcheCcagGetResponse = GetMarchesParCcagMarcheCcagGetResponses[keyof GetMarchesParCcagMarcheCcagGetResponses];

export type GetIndicateursMarcheIndicateursGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/indicateurs';
};

export type GetIndicateursMarcheIndicateursGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIndicateursMarcheIndicateursGetError = GetIndicateursMarcheIndicateursGetErrors[keyof GetIndicateursMarcheIndicateursGetErrors];

export type GetIndicateursMarcheIndicateursGetResponses = {
    /**
     * Successful Response
     */
    200: IndicateursDto;
};

export type GetIndicateursMarcheIndicateursGetResponse = GetIndicateursMarcheIndicateursGetResponses[keyof GetIndicateursMarcheIndicateursGetResponses];

export type GetMarchesParDepartementMarcheDepartementGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/marche/departement';
};

export type GetMarchesParDepartementMarcheDepartementGetResponses = {
    /**
     * Response Get Marches Par Departement Marche Departement Get
     * Successful Response
     */
    200: Array<MarcheDepartementDto>;
};

export type GetMarchesParDepartementMarcheDepartementGetResponse = GetMarchesParDepartementMarcheDepartementGetResponses[keyof GetMarchesParDepartementMarcheDepartementGetResponses];

export type GetListeConcessionsContratConcessionGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/contrat-concession/';
};

export type GetListeConcessionsContratConcessionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListeConcessionsContratConcessionGetError = GetListeConcessionsContratConcessionGetErrors[keyof GetListeConcessionsContratConcessionGetErrors];

export type GetListeConcessionsContratConcessionGetResponses = {
    /**
     * Response Get Liste Concessions Contrat Concession  Get
     * Successful Response
     */
    200: Array<ContratConcessionDto>;
};

export type GetListeConcessionsContratConcessionGetResponse = GetListeConcessionsContratConcessionGetResponses[keyof GetListeConcessionsContratConcessionGetResponses];

export type ListAcheteursStructureAcheteurGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/structure/acheteur';
};

export type ListAcheteursStructureAcheteurGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAcheteursStructureAcheteurGetError = ListAcheteursStructureAcheteurGetErrors[keyof ListAcheteursStructureAcheteurGetErrors];

export type ListAcheteursStructureAcheteurGetResponses = {
    /**
     * Response List Acheteurs Structure Acheteur Get
     * Successful Response
     */
    200: Array<StructureAggMarchesDto>;
};

export type ListAcheteursStructureAcheteurGetResponse = ListAcheteursStructureAcheteurGetResponses[keyof ListAcheteursStructureAcheteurGetResponses];

export type ListVendeursStructureVendeurGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/structure/vendeur';
};

export type ListVendeursStructureVendeurGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListVendeursStructureVendeurGetError = ListVendeursStructureVendeurGetErrors[keyof ListVendeursStructureVendeurGetErrors];

export type ListVendeursStructureVendeurGetResponses = {
    /**
     * Response List Vendeurs Structure Vendeur Get
     * Successful Response
     */
    200: Array<StructureAggMarchesDto>;
};

export type ListVendeursStructureVendeurGetResponse = ListVendeursStructureVendeurGetResponses[keyof ListVendeursStructureVendeurGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};
