// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * ActeSousTraitanceDto
 */
export type ActeSousTraitanceDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: number;
    sous_traitant: StructureDto;
    /**
     * Duree Mois
     */
    duree_mois: number | null;
    /**
     * Date Notification
     */
    date_notification: Date;
    /**
     * Date Publication
     */
    date_publication: Date;
    /**
     * Montant
     */
    montant: string;
    variation_prix: VariationPrix | null;
};

/**
 * CCAG
 */
export const Ccag = {
    TRAVAUX: 'Travaux',
    'MAITRISE_D_ŒUVRE': "Maitrise d'œuvre",
    FOURNITURES_COURANTES_ET_SERVICES: 'Fournitures courantes et services',
    'MARCHÉS_INDUSTRIELS': 'Marchés industriels',
    PRESTATIONS_INTELLECTUELLES: 'Prestations intellectuelles',
    'TECHNIQUES_DE_L_INFORMATION_ET_DE_LA_COMMUNICATION': "Techniques de l'information et de la communication",
    PAS_DE_CCAG: 'Pas de CCAG'
} as const;

/**
 * CCAG
 */
export type Ccag = typeof Ccag[keyof typeof Ccag];

/**
 * CategorieMarche
 */
export const CategorieMarche = {
    TRAVAUX: 'Travaux',
    FOURNITURES: 'Fournitures',
    SERVICES: 'Services'
} as const;

/**
 * CategorieMarche
 */
export type CategorieMarche = typeof CategorieMarche[keyof typeof CategorieMarche];

/**
 * CategoriesDto
 */
export type CategoriesDto = {
    categorie: CategorieMarche;
    /**
     * Mois
     */
    mois: string;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * ConsiderationsEnvironnementales
 */
export const ConsiderationsEnvironnementales = {
    'CRITÈRE_ENVIRONNEMENTAL': 'Critère environnemental',
    CLAUSE_ENVIRONNEMENTALE: 'Clause environnementale',
    'PAS_DE_CONSIDÉRATION_ENVIRONNEMENTALE': 'Pas de considération environnementale'
} as const;

/**
 * ConsiderationsEnvironnementales
 */
export type ConsiderationsEnvironnementales = typeof ConsiderationsEnvironnementales[keyof typeof ConsiderationsEnvironnementales];

/**
 * ConsiderationsSociales
 */
export const ConsiderationsSociales = {
    'CRITÈRE_SOCIAL': 'Critère social',
    CLAUSE_SOCIALE: 'Clause sociale',
    'MARCHÉ_RÉSERVÉ': 'Marché réservé',
    'CONCESSION_RÉSERVÉE': 'Concession réservée',
    'PAS_DE_CONSIDÉRATION_SOCIALE': 'Pas de considération sociale'
} as const;

/**
 * ConsiderationsSociales
 */
export type ConsiderationsSociales = typeof ConsiderationsSociales[keyof typeof ConsiderationsSociales];

/**
 * ContratConcessionDto
 */
export type ContratConcessionDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: string;
    autorite_concedante: StructureDto;
    nature: NatureConcession | null;
    /**
     * Objet
     */
    objet: string;
    procedure: ProcedureConcession | null;
    /**
     * Duree Mois
     */
    duree_mois: number;
    /**
     * Duree Mois Initiale
     */
    duree_mois_initiale: number;
    /**
     * Date Signature
     */
    date_signature: Date;
    /**
     * Date Publication
     */
    date_publication: Date;
    /**
     * Date Debut Execution
     */
    date_debut_execution: Date;
    /**
     * Valeur Globale
     */
    valeur_globale: string;
    /**
     * Valeur Globale Initiale
     */
    valeur_globale_initiale: string;
    /**
     * Montant Subvention Publique
     */
    montant_subvention_publique: string;
    /**
     * Donnees Execution
     */
    donnees_execution?: Array<DonneeExecutionDto>;
    /**
     * Concessionnaires
     */
    concessionnaires: Array<StructureDto>;
    /**
     * Considerations Sociales
     */
    considerations_sociales: Array<ConsiderationsSociales>;
    /**
     * Considerations Environnementales
     */
    considerations_environnementales: Array<ConsiderationsEnvironnementales>;
};

/**
 * DecpMalFormeDto
 */
export type DecpMalFormeDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Decp
     */
    decp: {
        [key: string]: unknown;
    };
    /**
     * Erreurs
     */
    erreurs: Array<ErreurDto>;
};

/**
 * DonneeExecutionDto
 */
export type DonneeExecutionDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: number;
    /**
     * Date Publication
     */
    date_publication: Date;
    /**
     * Depenses Investissement
     */
    depenses_investissement: string;
    /**
     * Tarifs
     */
    tarifs: Array<TarifDto>;
};

/**
 * ErreurDto
 */
export type ErreurDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Type
     */
    type: string;
    /**
     * Localisation
     */
    localisation: string;
    /**
     * Message
     */
    message: string;
};

/**
 * FormePrix
 */
export const FormePrix = {
    UNITAIRE: 'Unitaire',
    FORFAITAIRE: 'Forfaitaire',
    MIXTE: 'Mixte'
} as const;

/**
 * FormePrix
 */
export type FormePrix = typeof FormePrix[keyof typeof FormePrix];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IndicateursDto
 */
export type IndicateursDto = {
    /**
     * Periode
     */
    periode: number | null;
    /**
     * Nb Contrats
     */
    nb_contrats: number;
    /**
     * Montant Total
     */
    montant_total: string;
    /**
     * Nb Acheteurs
     */
    nb_acheteurs: number;
    /**
     * Nb Fournisseurs
     */
    nb_fournisseurs: number;
    /**
     * Nb Sous Traitance
     */
    nb_sous_traitance: number;
    /**
     * Nb Considerations Sociale Env
     */
    nb_considerations_sociale_env: number;
    /**
     * Nb Considerations Env
     */
    nb_considerations_env: number;
    /**
     * Nb Considerations Sociales
     */
    nb_considerations_sociales: number;
    /**
     * Nb Innovant
     */
    nb_innovant: number;
};

/**
 * LieuDto
 */
export type LieuDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Code
     */
    code: string;
    type_code: TypeCodeLieu;
};

/**
 * MarcheAllegeDto
 */
export type MarcheAllegeDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: string;
    acheteur: StructureDto;
    /**
     * Objet
     */
    objet: string;
    /**
     * Cpv
     *
     * Nomenclature européenne permettant d'identifier les catégories de biens et de service faisant l'objet du marché (http://simap.ted.europa.eu/web/simap/cpv). Exemple: 45112500 (même si toléré, il préférable d'omettre le caractère de contrôle (-9))
     */
    cpv: string;
    categorie: CategorieMarche;
    /**
     * Sous Traitance Declaree
     */
    sous_traitance_declaree: boolean;
    /**
     * Actes Sous Traitance
     */
    actes_sous_traitance: Array<ActeSousTraitanceDto>;
    /**
     * Duree Mois
     */
    duree_mois: number;
    /**
     * Date Notification
     */
    date_notification: Date;
    /**
     * Montant
     */
    montant: string;
    /**
     * Titulaires
     */
    titulaires: Array<StructureDto>;
    /**
     * Considerations Sociales
     */
    considerations_sociales: Array<ConsiderationsSociales>;
    /**
     * Considerations Environnementales
     */
    considerations_environnementales: Array<ConsiderationsEnvironnementales>;
};

/**
 * MarcheCategorieDepartementDto
 */
export type MarcheCategorieDepartementDto = {
    categorie: CategorieMarche;
    /**
     * Code
     */
    code: string;
    /**
     * Montant
     */
    montant: string;
};

/**
 * MarcheCcagDto
 */
export type MarcheCcagDto = {
    ccag: Ccag | null;
    categorie: CategorieMarche;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * MarcheDepartementDto
 */
export type MarcheDepartementDto = {
    /**
     * Code
     */
    code: string;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * MarcheDto
 */
export type MarcheDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: string;
    acheteur: StructureDto;
    nature: NatureMarche;
    /**
     * Objet
     */
    objet: string;
    /**
     * Cpv
     *
     * Nomenclature européenne permettant d'identifier les catégories de biens et de service faisant l'objet du marché (http://simap.ted.europa.eu/web/simap/cpv). Exemple: 45112500 (même si toléré, il préférable d'omettre le caractère de contrôle (-9))
     */
    cpv: string;
    categorie: CategorieMarche;
    /**
     * Techniques Achat
     */
    techniques_achat: Array<TechniqueAchat>;
    /**
     * Modalites Execution
     */
    modalites_execution: Array<ModaliteExecution>;
    accord_cadre: MarcheDto | null;
    /**
     * Marche Innovant
     */
    marche_innovant: boolean;
    /**
     * Ccag
     *
     * Cahiers des clauses administratives générales de référence du marché public
     */
    ccag: number | null;
    /**
     * Offres Recues
     *
     * Nombre d'offres reçues par l'acheteur de la part des soumissionnaires. Comprend aussi les offres irrégulières, inacceptables, inappropriées et anormalement basses.
     */
    offres_recues: number | null;
    /**
     * Attribution Avance
     *
     * Une avance a été attribuée au titulaire principal du marché public
     */
    attribution_avance: boolean;
    /**
     * Taux Avance
     *
     * Taux de l'avance attribuée au titulaire principal du marché public par rapport au montant du marché (O.1 = 10 % du montant du marché). En fonction de la valeur de attributionAvance, une valeur égale à 0 signifie soit qu'aucune avance n'a été accordée (si attributionAvance=false), soit que le taux de l'avance n'est pas connu (si attributionAvance=true).
     */
    taux_avance: string;
    type_groupement_operateurs: TypeGroupementOperateur | null;
    /**
     * Sous Traitance Declaree
     */
    sous_traitance_declaree: boolean;
    /**
     * Actes Sous Traitance
     */
    actes_sous_traitance: Array<ActeSousTraitanceDto>;
    procedure: ProcedureMarche | null;
    lieu: LieuDto;
    /**
     * Duree Mois
     */
    duree_mois: number;
    /**
     * Duree Mois Initiale
     */
    duree_mois_initiale: number;
    /**
     * Date Notification
     */
    date_notification: Date;
    /**
     * Date Publication
     */
    date_publication: Date | null;
    /**
     * Montant
     */
    montant: string;
    /**
     * Montant Initial
     */
    montant_initial: string;
    /**
     * Type Prix
     */
    type_prix: Array<TypePrix> | null;
    forme_prix: FormePrix | null;
    /**
     * Origine Ue
     */
    origine_ue: string | null;
    /**
     * Origine France
     */
    origine_france: string | null;
    /**
     * Titulaires
     */
    titulaires: Array<StructureDto>;
    /**
     * Considerations Sociales
     */
    considerations_sociales: Array<ConsiderationsSociales>;
    /**
     * Considerations Environnementales
     */
    considerations_environnementales: Array<ConsiderationsEnvironnementales>;
    /**
     * Modifications
     */
    modifications: Array<ModificationMarcheDto>;
};

/**
 * MarcheNatureDto
 */
export type MarcheNatureDto = {
    /**
     * Mois
     */
    mois: string;
    /**
     * Nature
     */
    nature: number;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * MarcheProcedureDto
 */
export type MarcheProcedureDto = {
    procedure: ProcedureMarche | null;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * ModaliteExecution
 */
export const ModaliteExecution = {
    TRANCHES: 'Tranches',
    BONS_DE_COMMANDE: 'Bons de commande',
    'MARCHÉS_SUBSÉQUENTS': 'Marchés subséquents',
    SANS_OBJET: 'Sans objet'
} as const;

/**
 * ModaliteExecution
 */
export type ModaliteExecution = typeof ModaliteExecution[keyof typeof ModaliteExecution];

/**
 * ModificationMarcheDto
 */
export type ModificationMarcheDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: number;
    /**
     * Duree Mois
     */
    duree_mois: number | null;
    /**
     * Date Notification
     */
    date_notification: Date;
    /**
     * Date Publication
     */
    date_publication: Date;
    /**
     * Montant
     */
    montant: string | null;
    /**
     * Titulaires
     */
    titulaires: Array<StructureDto>;
};

/**
 * NatureConcession
 */
export const NatureConcession = {
    CONCESSION_DE_TRAVAUX: 'Concession de travaux',
    CONCESSION_DE_SERVICE: 'Concession de service',
    CONCESSION_DE_SERVICE_PUBLIC: 'Concession de service public',
    'DÉLÉGATION_DE_SERVICE_PUBLIC': 'Délégation de service public'
} as const;

/**
 * NatureConcession
 */
export type NatureConcession = typeof NatureConcession[keyof typeof NatureConcession];

/**
 * NatureMarche
 */
export const NatureMarche = {
    'MARCHÉ': 'Marché',
    'MARCHÉ_DE_PARTENARIAT': 'Marché de partenariat',
    'MARCHÉ_DE_DÉFENSE_OU_DE_SÉCURITÉ': 'Marché de défense ou de sécurité'
} as const;

/**
 * NatureMarche
 */
export type NatureMarche = typeof NatureMarche[keyof typeof NatureMarche];

/**
 * ProcedureConcession
 */
export const ProcedureConcession = {
    'PROCÉDURE_NÉGOCIÉE_OUVERTE': 'Procédure négociée ouverte',
    'PROCÉDURE_NON_NÉGOCIÉE_OUVERTE': 'Procédure non négociée ouverte',
    'PROCÉDURE_NÉGOCIÉE_RESTREINTE': 'Procédure négociée restreinte',
    'PROCÉDURE_NON_NÉGOCIÉE_RESTREINTE': 'Procédure non négociée restreinte'
} as const;

/**
 * ProcedureConcession
 */
export type ProcedureConcession = typeof ProcedureConcession[keyof typeof ProcedureConcession];

/**
 * ProcedureMarche
 */
export const ProcedureMarche = {
    'PROCÉDURE_ADAPTÉE': 'Procédure adaptée',
    'APPEL_D_OFFRES_OUVERT': "Appel d'offres ouvert",
    'APPEL_D_OFFRES_RESTREINT': "Appel d'offres restreint",
    'MARCHÉ_PASSÉ_SANS_PUBLICITÉ_NI_MISE_EN_CONCURRENCE_PRÉALABLE': 'Marché passé sans publicité ni mise en concurrence préalable',
    'DIALOGUE_COMPÉTITIF': 'Dialogue compétitif',
    'PROCÉDURE_AVEC_NÉGOCIATION': 'Procédure avec négociation'
} as const;

/**
 * ProcedureMarche
 */
export type ProcedureMarche = typeof ProcedureMarche[keyof typeof ProcedureMarche];

/**
 * StatsErreursDto
 */
export type StatsErreursDto = {
    /**
     * Erreur
     */
    erreur: string;
    /**
     * Nombre
     */
    nombre: number;
    /**
     * Localisation
     */
    localisation: string;
    /**
     * Type
     */
    type: string;
};

/**
 * StructureAggMarchesDto
 */
export type StructureAggMarchesDto = {
    structure: StructureDto;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nb Contrats
     */
    nb_contrats: number;
};

/**
 * StructureDto
 */
export type StructureDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Identifiant
     */
    identifiant: string;
    /**
     * Type Identifiant
     */
    type_identifiant: string;
    /**
     * Nom
     */
    nom: string | null;
    /**
     * Vendeur
     */
    vendeur: boolean;
    /**
     * Acheteur
     */
    acheteur: boolean;
};

/**
 * StructureEtendueDto
 */
export type StructureEtendueDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Identifiant
     */
    identifiant: string;
    /**
     * Type Identifiant
     */
    type_identifiant: string;
    /**
     * Nom
     */
    nom: string | null;
    /**
     * Vendeur
     */
    vendeur: boolean;
    /**
     * Acheteur
     */
    acheteur: boolean;
    /**
     * Denomination
     */
    denomination?: string | null;
    /**
     * Sigle
     */
    sigle?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Cat Juridique
     */
    cat_juridique?: string | null;
    /**
     * Naf
     */
    naf?: string | null;
    /**
     * Effectifs
     */
    effectifs?: string | null;
    /**
     * Date Effectifs
     */
    date_effectifs?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Date Creation
     */
    date_creation?: Date | null;
};

/**
 * TarifDto
 */
export type TarifDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Intitule
     */
    intitule: string;
    /**
     * Tarif
     */
    tarif: string;
};

/**
 * TechniqueAchat
 */
export const TechniqueAchat = {
    ACCORD_CADRE: 'Accord-cadre',
    CONCOURS: 'Concours',
    'SYSTÈME_DE_QUALIFICATION': 'Système de qualification',
    'SYSTÈME_D_ACQUISITION_DYNAMIQUE': "Système d'acquisition dynamique",
    'CATALOGUE_ÉLECTRONIQUE': 'Catalogue électronique',
    'ENCHÈRE_ÉLECTRONIQUE': 'Enchère électronique',
    SANS_OBJET: 'Sans objet'
} as const;

/**
 * TechniqueAchat
 */
export type TechniqueAchat = typeof TechniqueAchat[keyof typeof TechniqueAchat];

/**
 * TypeCodeLieu
 */
export const TypeCodeLieu = {
    CODE_POSTAL: 'Code postal',
    CODE_COMMUNE: 'Code commune',
    CODE_ARRONDISSEMENT: 'Code arrondissement',
    CODE_CANTON: 'Code canton',
    'CODE_DÉPARTEMENT': 'Code département',
    'CODE_RÉGION': 'Code région',
    CODE_PAYS: 'Code pays'
} as const;

/**
 * TypeCodeLieu
 */
export type TypeCodeLieu = typeof TypeCodeLieu[keyof typeof TypeCodeLieu];

/**
 * TypeGroupementOperateur
 */
export const TypeGroupementOperateur = {
    CONJOINT: 'Conjoint',
    SOLIDAIRE: 'Solidaire',
    PAS_DE_GROUPEMENT: 'Pas de groupement'
} as const;

/**
 * TypeGroupementOperateur
 */
export type TypeGroupementOperateur = typeof TypeGroupementOperateur[keyof typeof TypeGroupementOperateur];

/**
 * TypePrix
 */
export const TypePrix = {
    'DÉFINITIF_FERME': 'Définitif ferme',
    'DÉFINITIF_ACTUALISABLE': 'Définitif actualisable',
    'DÉFINITIF_RÉVISABLE': 'Définitif révisable',
    PROVISOIRE: 'Provisoire'
} as const;

/**
 * TypePrix
 */
export type TypePrix = typeof TypePrix[keyof typeof TypePrix];

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VariationPrix
 */
export const VariationPrix = {
    FERME: 'Ferme',
    ACTUALISABLE: 'Actualisable',
    'RÉVISABLE': 'Révisable',
    NC: 'NC'
} as const;

/**
 * VariationPrix
 */
export type VariationPrix = typeof VariationPrix[keyof typeof VariationPrix];

export type GetErreursImportErreursImportGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Localisation
         */
        localisation?: string | null;
        /**
         * Type
         */
        type?: string | null;
    };
    url: '/erreurs-import/';
};

export type GetErreursImportErreursImportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetErreursImportErreursImportGetError = GetErreursImportErreursImportGetErrors[keyof GetErreursImportErreursImportGetErrors];

export type GetErreursImportErreursImportGetResponses = {
    /**
     * Response Get Erreurs Import Erreurs Import  Get
     *
     * Successful Response
     */
    200: Array<DecpMalFormeDto>;
};

export type GetErreursImportErreursImportGetResponse = GetErreursImportErreursImportGetResponses[keyof GetErreursImportErreursImportGetResponses];

export type GetStatsErreursErreursImportStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/erreurs-import/stats';
};

export type GetStatsErreursErreursImportStatsGetResponses = {
    /**
     * Response Get Stats Erreurs Erreurs Import Stats Get
     *
     * Successful Response
     */
    200: Array<StatsErreursDto>;
};

export type GetStatsErreursErreursImportStatsGetResponse = GetStatsErreursErreursImportStatsGetResponses[keyof GetStatsErreursErreursImportStatsGetResponses];

export type GetListeMarchesMarcheGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
        /**
         * Objet
         */
        objet?: string | null;
        /**
         * Cpv
         */
        cpv?: string | null;
        /**
         * Code Lieu
         */
        code_lieu?: number | null;
        /**
         * Forme Prix
         */
        forme_prix?: FormePrix | null;
        /**
         * Type Marche
         */
        type_marche?: NatureMarche | null;
        /**
         * Procedure
         */
        procedure?: ProcedureMarche | null;
        /**
         * Technique Achat
         */
        technique_achat?: TechniqueAchat | null;
        /**
         * Consideration
         */
        consideration?: ConsiderationsEnvironnementales | ConsiderationsSociales | null;
        /**
         * Montant Max
         */
        montant_max?: number | null;
        /**
         * Montant Min
         */
        montant_min?: number | null;
        /**
         * Duree Max
         */
        duree_max?: number | null;
        /**
         * Duree Min
         */
        duree_min?: number | null;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
    };
    url: '/marche/';
};

export type GetListeMarchesMarcheGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListeMarchesMarcheGetError = GetListeMarchesMarcheGetErrors[keyof GetListeMarchesMarcheGetErrors];

export type GetListeMarchesMarcheGetResponses = {
    /**
     * Response Get Liste Marches Marche  Get
     *
     * Successful Response
     */
    200: Array<MarcheAllegeDto>;
};

export type GetListeMarchesMarcheGetResponse = GetListeMarchesMarcheGetResponses[keyof GetListeMarchesMarcheGetResponses];

export type GetMarchesParProcedureMarcheProcedureGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/procedure';
};

export type GetMarchesParProcedureMarcheProcedureGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarchesParProcedureMarcheProcedureGetError = GetMarchesParProcedureMarcheProcedureGetErrors[keyof GetMarchesParProcedureMarcheProcedureGetErrors];

export type GetMarchesParProcedureMarcheProcedureGetResponses = {
    /**
     * Response Get Marches Par Procedure Marche Procedure Get
     *
     * Successful Response
     */
    200: Array<MarcheProcedureDto>;
};

export type GetMarchesParProcedureMarcheProcedureGetResponse = GetMarchesParProcedureMarcheProcedureGetResponses[keyof GetMarchesParProcedureMarcheProcedureGetResponses];

export type GetMarchesParNatureMarcheNatureGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/nature';
};

export type GetMarchesParNatureMarcheNatureGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarchesParNatureMarcheNatureGetError = GetMarchesParNatureMarcheNatureGetErrors[keyof GetMarchesParNatureMarcheNatureGetErrors];

export type GetMarchesParNatureMarcheNatureGetResponses = {
    /**
     * Response Get Marches Par Nature Marche Nature Get
     *
     * Successful Response
     */
    200: Array<MarcheNatureDto>;
};

export type GetMarchesParNatureMarcheNatureGetResponse = GetMarchesParNatureMarcheNatureGetResponses[keyof GetMarchesParNatureMarcheNatureGetResponses];

export type GetMarchesParCcagMarcheCcagGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/ccag';
};

export type GetMarchesParCcagMarcheCcagGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarchesParCcagMarcheCcagGetError = GetMarchesParCcagMarcheCcagGetErrors[keyof GetMarchesParCcagMarcheCcagGetErrors];

export type GetMarchesParCcagMarcheCcagGetResponses = {
    /**
     * Response Get Marches Par Ccag Marche Ccag Get
     *
     * Successful Response
     */
    200: Array<MarcheCcagDto>;
};

export type GetMarchesParCcagMarcheCcagGetResponse = GetMarchesParCcagMarcheCcagGetResponses[keyof GetMarchesParCcagMarcheCcagGetResponses];

export type GetIndicateursMarcheIndicateursGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
        /**
         * Objet
         */
        objet?: string | null;
        /**
         * Cpv
         */
        cpv?: string | null;
        /**
         * Code Lieu
         */
        code_lieu?: number | null;
        /**
         * Forme Prix
         */
        forme_prix?: FormePrix | null;
        /**
         * Type Marche
         */
        type_marche?: NatureMarche | null;
        /**
         * Procedure
         */
        procedure?: ProcedureMarche | null;
        /**
         * Technique Achat
         */
        technique_achat?: TechniqueAchat | null;
        /**
         * Consideration
         */
        consideration?: ConsiderationsEnvironnementales | ConsiderationsSociales | null;
        /**
         * Montant Max
         */
        montant_max?: number | null;
        /**
         * Montant Min
         */
        montant_min?: number | null;
        /**
         * Duree Max
         */
        duree_max?: number | null;
        /**
         * Duree Min
         */
        duree_min?: number | null;
    };
    url: '/marche/indicateurs';
};

export type GetIndicateursMarcheIndicateursGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIndicateursMarcheIndicateursGetError = GetIndicateursMarcheIndicateursGetErrors[keyof GetIndicateursMarcheIndicateursGetErrors];

export type GetIndicateursMarcheIndicateursGetResponses = {
    /**
     * Successful Response
     */
    200: IndicateursDto;
};

export type GetIndicateursMarcheIndicateursGetResponse = GetIndicateursMarcheIndicateursGetResponses[keyof GetIndicateursMarcheIndicateursGetResponses];

export type GetMarchesParDepartementMarcheDepartementGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/marche/departement';
};

export type GetMarchesParDepartementMarcheDepartementGetResponses = {
    /**
     * Response Get Marches Par Departement Marche Departement Get
     *
     * Successful Response
     */
    200: Array<MarcheDepartementDto>;
};

export type GetMarchesParDepartementMarcheDepartementGetResponse = GetMarchesParDepartementMarcheDepartementGetResponses[keyof GetMarchesParDepartementMarcheDepartementGetResponses];

export type GetCategorieDepartementMarcheCategorieDepartementGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/marche/categorie-departement';
};

export type GetCategorieDepartementMarcheCategorieDepartementGetResponses = {
    /**
     * Response Get Categorie Departement Marche Categorie Departement Get
     *
     * Successful Response
     */
    200: Array<MarcheCategorieDepartementDto>;
};

export type GetCategorieDepartementMarcheCategorieDepartementGetResponse = GetCategorieDepartementMarcheCategorieDepartementGetResponses[keyof GetCategorieDepartementMarcheCategorieDepartementGetResponses];

export type GetCategoriesMarcheCategorieGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/categorie';
};

export type GetCategoriesMarcheCategorieGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCategoriesMarcheCategorieGetError = GetCategoriesMarcheCategorieGetErrors[keyof GetCategoriesMarcheCategorieGetErrors];

export type GetCategoriesMarcheCategorieGetResponses = {
    /**
     * Response Get Categories Marche Categorie Get
     *
     * Successful Response
     */
    200: Array<CategoriesDto>;
};

export type GetCategoriesMarcheCategorieGetResponse = GetCategoriesMarcheCategorieGetResponses[keyof GetCategoriesMarcheCategorieGetResponses];

export type GetMarcheMarcheUidGetData = {
    body?: never;
    path: {
        /**
         * Uid
         */
        uid: number;
    };
    query?: never;
    url: '/marche/{uid}';
};

export type GetMarcheMarcheUidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarcheMarcheUidGetError = GetMarcheMarcheUidGetErrors[keyof GetMarcheMarcheUidGetErrors];

export type GetMarcheMarcheUidGetResponses = {
    /**
     * Successful Response
     */
    200: MarcheDto;
};

export type GetMarcheMarcheUidGetResponse = GetMarcheMarcheUidGetResponses[keyof GetMarcheMarcheUidGetResponses];

export type GetListeConcessionsContratConcessionGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Autorite Concedante Uid
         */
        autorite_concedante_uid?: string | null;
        /**
         * Concessionnaire Uid
         */
        concessionnaire_uid?: string | null;
    };
    url: '/contrat-concession/';
};

export type GetListeConcessionsContratConcessionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListeConcessionsContratConcessionGetError = GetListeConcessionsContratConcessionGetErrors[keyof GetListeConcessionsContratConcessionGetErrors];

export type GetListeConcessionsContratConcessionGetResponses = {
    /**
     * Response Get Liste Concessions Contrat Concession  Get
     *
     * Successful Response
     */
    200: Array<ContratConcessionDto>;
};

export type GetListeConcessionsContratConcessionGetResponse = GetListeConcessionsContratConcessionGetResponses[keyof GetListeConcessionsContratConcessionGetResponses];

export type GetConcessionContratConcessionUidGetData = {
    body?: never;
    path: {
        /**
         * Uid
         */
        uid: number;
    };
    query?: never;
    url: '/contrat-concession/{uid}';
};

export type GetConcessionContratConcessionUidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConcessionContratConcessionUidGetError = GetConcessionContratConcessionUidGetErrors[keyof GetConcessionContratConcessionUidGetErrors];

export type GetConcessionContratConcessionUidGetResponses = {
    /**
     * Successful Response
     */
    200: ContratConcessionDto;
};

export type GetConcessionContratConcessionUidGetResponse = GetConcessionContratConcessionUidGetResponses[keyof GetConcessionContratConcessionUidGetResponses];

export type ListStructuresStructureGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Nom
         */
        nom?: string | null;
        /**
         * Is Acheteur
         */
        is_acheteur?: boolean;
        /**
         * Is Vendeur
         */
        is_vendeur?: boolean;
    };
    url: '/structure/';
};

export type ListStructuresStructureGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListStructuresStructureGetError = ListStructuresStructureGetErrors[keyof ListStructuresStructureGetErrors];

export type ListStructuresStructureGetResponses = {
    /**
     * Response List Structures Structure  Get
     *
     * Successful Response
     */
    200: Array<StructureDto>;
};

export type ListStructuresStructureGetResponse = ListStructuresStructureGetResponses[keyof ListStructuresStructureGetResponses];

export type ListAcheteursStructureAcheteurGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: number | null;
        /**
         * Categorie
         */
        categorie?: CategorieMarche | null;
    };
    url: '/structure/acheteur';
};

export type ListAcheteursStructureAcheteurGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAcheteursStructureAcheteurGetError = ListAcheteursStructureAcheteurGetErrors[keyof ListAcheteursStructureAcheteurGetErrors];

export type ListAcheteursStructureAcheteurGetResponses = {
    /**
     * Response List Acheteurs Structure Acheteur Get
     *
     * Successful Response
     */
    200: Array<StructureAggMarchesDto>;
};

export type ListAcheteursStructureAcheteurGetResponse = ListAcheteursStructureAcheteurGetResponses[keyof ListAcheteursStructureAcheteurGetResponses];

export type ListVendeursStructureVendeurGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: number | null;
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Categorie
         */
        categorie?: CategorieMarche | null;
    };
    url: '/structure/vendeur';
};

export type ListVendeursStructureVendeurGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListVendeursStructureVendeurGetError = ListVendeursStructureVendeurGetErrors[keyof ListVendeursStructureVendeurGetErrors];

export type ListVendeursStructureVendeurGetResponses = {
    /**
     * Response List Vendeurs Structure Vendeur Get
     *
     * Successful Response
     */
    200: Array<StructureAggMarchesDto>;
};

export type ListVendeursStructureVendeurGetResponse = ListVendeursStructureVendeurGetResponses[keyof ListVendeursStructureVendeurGetResponses];

export type GetStructureStructureUidGetData = {
    body?: never;
    path: {
        /**
         * Uid
         */
        uid: number;
    };
    query?: never;
    url: '/structure/{uid}';
};

export type GetStructureStructureUidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStructureStructureUidGetError = GetStructureStructureUidGetErrors[keyof GetStructureStructureUidGetErrors];

export type GetStructureStructureUidGetResponses = {
    /**
     * Successful Response
     */
    200: StructureEtendueDto;
};

export type GetStructureStructureUidGetResponse = GetStructureStructureUidGetResponses[keyof GetStructureStructureUidGetResponses];
