// This file is auto-generated by @hey-api/openapi-ts

/**
 * ActeSousTraitanceDto
 */
export type ActeSousTraitanceDto = {
    /**
     * Uid
     */
    uid: number;
};

/**
 * ContratConcessionDto
 */
export type ContratConcessionDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: number;
    autorite_concedante: StructureDto;
    /**
     * Objet
     */
    objet: string;
};

/**
 * DecpMalFormeDto
 */
export type DecpMalFormeDto = {
    /**
     * Decp
     */
    decp: {
        [key: string]: unknown;
    };
    /**
     * Erreurs
     */
    erreurs: Array<ErreurDto>;
};

/**
 * ErreurDto
 */
export type ErreurDto = {
    /**
     * Type
     */
    type: string;
    /**
     * Localisation
     */
    localisation: string;
    /**
     * Message
     */
    message: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IndicateursDto
 */
export type IndicateursDto = {
    /**
     * Periode
     */
    periode: number | null;
    /**
     * Nb Contrats
     */
    nb_contrats: number;
    /**
     * Montant Total
     */
    montant_total: string;
    /**
     * Nb Acheteurs
     */
    nb_acheteurs: number;
    /**
     * Nb Fournisseurs
     */
    nb_fournisseurs: number;
    /**
     * Nb Sous Traitance
     */
    nb_sous_traitance: number;
    /**
     * Nb Innovant
     */
    nb_innovant: number;
};

/**
 * MarcheAllegeDto
 */
export type MarcheAllegeDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: string;
    acheteur: StructureDto;
    /**
     * Objet
     */
    objet: string;
    /**
     * Cpv
     * Nomenclature européenne permettant d'identifier les catégories de biens et de service faisant l'objet du marché (http://simap.ted.europa.eu/web/simap/cpv). Exemple: 45112500 (même si toléré, il préférable d'omettre le caractère de contrôle (-9))
     */
    cpv: string;
    /**
     * Sous Traitance Declaree
     */
    sous_traitance_declaree: boolean;
    /**
     * Actes Sous Traitance
     */
    actes_sous_traitance: Array<ActeSousTraitanceDto>;
    /**
     * Date Notification
     */
    date_notification: Date;
    /**
     * Montant
     */
    montant: string;
    /**
     * Titulaires
     */
    titulaires: Array<StructureDto>;
};

/**
 * MarcheCcagDto
 */
export type MarcheCcagDto = {
    /**
     * Ccag
     */
    ccag: number | null;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * MarcheDepartementDto
 */
export type MarcheDepartementDto = {
    /**
     * Code
     */
    code: string;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * MarcheNatureDto
 */
export type MarcheNatureDto = {
    /**
     * Mois
     */
    mois: string;
    /**
     * Nature
     */
    nature: number;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * MarcheProcedureDto
 */
export type MarcheProcedureDto = {
    /**
     * Procedure
     */
    procedure: number | null;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nombre
     */
    nombre: number;
};

/**
 * StructureAggMarchesDto
 */
export type StructureAggMarchesDto = {
    structure: StructureDto;
    /**
     * Montant
     */
    montant: string;
    /**
     * Nb Contrats
     */
    nb_contrats: number;
};

/**
 * StructureDto
 */
export type StructureDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Identifiant
     */
    identifiant: string;
    /**
     * Type Identifiant
     */
    type_identifiant: string;
    /**
     * Nom
     */
    nom: string | null;
    /**
     * Vendeur
     */
    vendeur: boolean;
    /**
     * Acheteur
     */
    acheteur: boolean;
};

/**
 * StructureEtendueDto
 */
export type StructureEtendueDto = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Identifiant
     */
    identifiant: string;
    /**
     * Type Identifiant
     */
    type_identifiant: string;
    /**
     * Nom
     */
    nom: string | null;
    /**
     * Vendeur
     */
    vendeur: boolean;
    /**
     * Acheteur
     */
    acheteur: boolean;
    /**
     * Denomination
     */
    denomination?: string | null;
    /**
     * Sigle
     */
    sigle?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Cat Juridique
     */
    cat_juridique?: string | null;
    /**
     * Naf
     */
    naf?: string | null;
    /**
     * Effectifs
     */
    effectifs?: string | null;
    /**
     * Date Effectifs
     */
    date_effectifs?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetErreursImportErreursImportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/erreurs-import/';
};

export type GetErreursImportErreursImportGetResponses = {
    /**
     * Response Get Erreurs Import Erreurs Import  Get
     * Successful Response
     */
    200: Array<DecpMalFormeDto>;
};

export type GetErreursImportErreursImportGetResponse = GetErreursImportErreursImportGetResponses[keyof GetErreursImportErreursImportGetResponses];

export type GetListeMarchesMarcheGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/';
};

export type GetListeMarchesMarcheGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListeMarchesMarcheGetError = GetListeMarchesMarcheGetErrors[keyof GetListeMarchesMarcheGetErrors];

export type GetListeMarchesMarcheGetResponses = {
    /**
     * Response Get Liste Marches Marche  Get
     * Successful Response
     */
    200: Array<MarcheAllegeDto>;
};

export type GetListeMarchesMarcheGetResponse = GetListeMarchesMarcheGetResponses[keyof GetListeMarchesMarcheGetResponses];

export type GetMarchesParProcedureMarcheProcedureGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/procedure';
};

export type GetMarchesParProcedureMarcheProcedureGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarchesParProcedureMarcheProcedureGetError = GetMarchesParProcedureMarcheProcedureGetErrors[keyof GetMarchesParProcedureMarcheProcedureGetErrors];

export type GetMarchesParProcedureMarcheProcedureGetResponses = {
    /**
     * Response Get Marches Par Procedure Marche Procedure Get
     * Successful Response
     */
    200: Array<MarcheProcedureDto>;
};

export type GetMarchesParProcedureMarcheProcedureGetResponse = GetMarchesParProcedureMarcheProcedureGetResponses[keyof GetMarchesParProcedureMarcheProcedureGetResponses];

export type GetMarchesParNatureMarcheNatureGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/nature';
};

export type GetMarchesParNatureMarcheNatureGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarchesParNatureMarcheNatureGetError = GetMarchesParNatureMarcheNatureGetErrors[keyof GetMarchesParNatureMarcheNatureGetErrors];

export type GetMarchesParNatureMarcheNatureGetResponses = {
    /**
     * Response Get Marches Par Nature Marche Nature Get
     * Successful Response
     */
    200: Array<MarcheNatureDto>;
};

export type GetMarchesParNatureMarcheNatureGetResponse = GetMarchesParNatureMarcheNatureGetResponses[keyof GetMarchesParNatureMarcheNatureGetResponses];

export type GetMarchesParCcagMarcheCcagGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/ccag';
};

export type GetMarchesParCcagMarcheCcagGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMarchesParCcagMarcheCcagGetError = GetMarchesParCcagMarcheCcagGetErrors[keyof GetMarchesParCcagMarcheCcagGetErrors];

export type GetMarchesParCcagMarcheCcagGetResponses = {
    /**
     * Response Get Marches Par Ccag Marche Ccag Get
     * Successful Response
     */
    200: Array<MarcheCcagDto>;
};

export type GetMarchesParCcagMarcheCcagGetResponse = GetMarchesParCcagMarcheCcagGetResponses[keyof GetMarchesParCcagMarcheCcagGetResponses];

export type GetIndicateursMarcheIndicateursGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date Debut
         */
        date_debut?: Date | null;
        /**
         * Date Fin
         */
        date_fin?: Date | null;
        /**
         * Acheteur Uid
         */
        acheteur_uid?: string | null;
        /**
         * Vendeur Uid
         */
        vendeur_uid?: string | null;
    };
    url: '/marche/indicateurs';
};

export type GetIndicateursMarcheIndicateursGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIndicateursMarcheIndicateursGetError = GetIndicateursMarcheIndicateursGetErrors[keyof GetIndicateursMarcheIndicateursGetErrors];

export type GetIndicateursMarcheIndicateursGetResponses = {
    /**
     * Successful Response
     */
    200: IndicateursDto;
};

export type GetIndicateursMarcheIndicateursGetResponse = GetIndicateursMarcheIndicateursGetResponses[keyof GetIndicateursMarcheIndicateursGetResponses];

export type GetMarchesParDepartementMarcheDepartementGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/marche/departement';
};

export type GetMarchesParDepartementMarcheDepartementGetResponses = {
    /**
     * Response Get Marches Par Departement Marche Departement Get
     * Successful Response
     */
    200: Array<MarcheDepartementDto>;
};

export type GetMarchesParDepartementMarcheDepartementGetResponse = GetMarchesParDepartementMarcheDepartementGetResponses[keyof GetMarchesParDepartementMarcheDepartementGetResponses];

export type GetListeConcessionsContratConcessionGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/contrat-concession/';
};

export type GetListeConcessionsContratConcessionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListeConcessionsContratConcessionGetError = GetListeConcessionsContratConcessionGetErrors[keyof GetListeConcessionsContratConcessionGetErrors];

export type GetListeConcessionsContratConcessionGetResponses = {
    /**
     * Response Get Liste Concessions Contrat Concession  Get
     * Successful Response
     */
    200: Array<ContratConcessionDto>;
};

export type GetListeConcessionsContratConcessionGetResponse = GetListeConcessionsContratConcessionGetResponses[keyof GetListeConcessionsContratConcessionGetResponses];

export type ListAcheteursStructureAcheteurGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/structure/acheteur';
};

export type ListAcheteursStructureAcheteurGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAcheteursStructureAcheteurGetError = ListAcheteursStructureAcheteurGetErrors[keyof ListAcheteursStructureAcheteurGetErrors];

export type ListAcheteursStructureAcheteurGetResponses = {
    /**
     * Response List Acheteurs Structure Acheteur Get
     * Successful Response
     */
    200: Array<StructureAggMarchesDto>;
};

export type ListAcheteursStructureAcheteurGetResponse = ListAcheteursStructureAcheteurGetResponses[keyof ListAcheteursStructureAcheteurGetResponses];

export type ListVendeursStructureVendeurGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
    };
    url: '/structure/vendeur';
};

export type ListVendeursStructureVendeurGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListVendeursStructureVendeurGetError = ListVendeursStructureVendeurGetErrors[keyof ListVendeursStructureVendeurGetErrors];

export type ListVendeursStructureVendeurGetResponses = {
    /**
     * Response List Vendeurs Structure Vendeur Get
     * Successful Response
     */
    200: Array<StructureAggMarchesDto>;
};

export type ListVendeursStructureVendeurGetResponse = ListVendeursStructureVendeurGetResponses[keyof ListVendeursStructureVendeurGetResponses];

export type GetStructureStructureUidGetData = {
    body?: never;
    path: {
        /**
         * Uid
         */
        uid: number;
    };
    query?: never;
    url: '/structure/{uid}';
};

export type GetStructureStructureUidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStructureStructureUidGetError = GetStructureStructureUidGetErrors[keyof GetStructureStructureUidGetErrors];

export type GetStructureStructureUidGetResponses = {
    /**
     * Successful Response
     */
    200: StructureEtendueDto;
};

export type GetStructureStructureUidGetResponse = GetStructureStructureUidGetResponses[keyof GetStructureStructureUidGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};