const listeDepartements = {
    '01': 'Ain',
    '48': 'Lozère',
    '02': 'Aisne',
    '49': 'Maine-et-Loire',
    '03': 'Allier',
    '50': 'Manche',
    '04': 'Alpes-de-Haute-Provence',
    '51': 'Marne',
    '05': 'Hautes-Alpes',
    '52': 'Haute-Marne',
    '06': 'Alpes-Maritimes',
    '53': 'Mayenne',
    '07': 'Ardèche',
    '54': 'Meurthe-et-Moselle',
    '08': 'Ardennes',
    '55': 'Meuse',
    '09': 'Ariège',
    '56': 'Morbihan',
    '10': 'Aube',
    '57': 'Moselle',
    '11': 'Aude',
    '58': 'Nièvre',
    '12': 'Aveyron',
    '59': 'Nord',
    '13': 'Bouches-du-Rhône',
    '60': 'Oise',
    '14': 'Calvados',
    '61': 'Orne',
    '15': 'Cantal',
    '62': 'Pas-de-Calais',
    '16': 'Charente',
    '63': 'Puy-de-Dôme',
    '17': 'Charente-Maritime',
    '64': 'Pyrénées-Atlantiques',
    '18': 'Cher',
    '65': 'Hautes-Pyrénées',
    '19': 'Corrèze',
    '66': 'Pyrénées-Orientales',
    '2A': 'Corse-du-Sud',
    '67': 'Bas-Rhin',
    '2B': 'Haute-Corse',
    '68': 'Haut-Rhin',
    '21': "Côte-d'Or",
    '69': 'Rhône',
    '22': "Côtes d'Armor",
    '70': 'Haute-Saône',
    '23': 'Creuse',
    '71': 'Saône-et-Loire',
    '24': 'Dordogne',
    '72': 'Sarthe',
    '25': 'Doubs',
    '73': 'Savoie',
    '26': 'Drôme',
    '74': 'Haute-Savoie',
    '27': 'Eure',
    '75': 'Paris',
    '28': 'Eure-et-Loir',
    '76': 'Seine-Maritime',
    '29': 'Finistère',
    '77': 'Seine-et-Marne',
    '30': 'Gard',
    '78': 'Yvelines',
    '31': 'Haute-Garonne',
    '79': 'Deux-Sèvres',
    '32': 'Gers',
    '80': 'Somme',
    '33': 'Gironde',
    '81': 'Tarn',
    '34': 'Hérault',
    '82': 'Tarn-et-Garonne',
    '35': 'Ille-et-Vilaine',
    '83': 'Var',
    '36': 'Indre',
    '84': 'Vaucluse',
    '37': 'Indre-et-Loire',
    '85': 'Vendée',
    '38': 'Isère',
    '86': 'Vienne',
    '39': 'Jura',
    '87': 'Haute-Vienne',
    '40': 'Landes',
    '88': 'Vosges',
    '41': 'Loir-et-Cher',
    '89': 'Yonne',
    '42': 'Loire',
    '90': 'Territoire de Belfort',
    '43': 'Haute-Loire',
    '91': 'Essonne',
    '44': 'Loire-Atlantique',
    '92': 'Hauts-de-Seine',
    '45': 'Loiret',
    '93': 'Seine-Saint-Denis',
    '46': 'Lot',
    '94': 'Val-de-Marne',
    '47': 'Lot-et-Garonne',
    '95': "Val-d'Oise",
    '971': 'Guadeloupe',
    '972': 'Martinique',
    '973': 'Guyane',
    '974': 'La Réunion',
    '976': 'Mayotte'
};

export function getNomDepartement(code: string): string {
    return listeDepartements[code];
}

export function getDepartementAvecNumeroAsListe() {
    return Object.entries(listeDepartements).map(([k, v]) => {
        return { value: `(${k}) ${v}`, code: parseInt(k) };
    });
}
