/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AchatDurable: typeof import('./src/components/dashboard/AchatDurable.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Badge: typeof import('primevue/badge')['default']
    BoutonIframe: typeof import('./src/components/BoutonIframe.vue')['default']
    Button: typeof import('primevue/button')['default']
    CarteAcheteursFournisseurs: typeof import('./src/components/dashboard/CarteAcheteursFournisseurs.vue')['default']
    CategoriePrincipaleDAchat: typeof import('./src/components/dashboard/CategoriePrincipaleDAchat.vue')['default']
    CCAG: typeof import('./src/components/dashboard/CCAG.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Departements: typeof import('./src/components/dashboard/Departements.vue')['default']
    DetailsAcheteur: typeof import('./src/components/DetailsAcheteur.vue')['default']
    DetailsFournisseur: typeof import('./src/components/DetailsFournisseur.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DistributionAchatsParDepartement: typeof import('./src/components/dashboard/DistributionAchatsParDepartement.vue')['default']
    DistributionTemporelleMarches: typeof import('./src/components/dashboard/DistributionTemporelleMarches.vue')['default']
    FiltreDates: typeof import('./src/components/FiltreDates.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Fluid: typeof import('primevue/fluid')['default']
    Graph: typeof import('./src/components/Graph.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IndicateursCles: typeof import('./src/components/dashboard/IndicateursCles.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    ListeConcessions: typeof import('./src/components/ListeConcessions.vue')['default']
    ListeMarches: typeof import('./src/components/ListeMarches.vue')['default']
    Message: typeof import('primevue/message')['default']
    ModaleConcession: typeof import('./src/components/ModaleConcession.vue')['default']
    ModaleMarche: typeof import('./src/components/ModaleMarche.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NatureContrats: typeof import('./src/components/dashboard/NatureContrats.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Procedure: typeof import('./src/components/dashboard/Procedure.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StructureSearchAutoComplete: typeof import('./src/components/StructureSearchAutoComplete.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    Top12: typeof import('./src/components/dashboard/Top12.vue')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
